name: Build (Lualatex)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    name: Build and log errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo release.dat
        run: echo "::debug::Writing 'version = build-${{ github.run_id }}-${{ github.run_number }}' to release.dat"
      - name: Update release.dat
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "release.dat"
          FILE_DATA: "version = build-${{ github.run_id }}-${{ github.run_number }}"
      - name: LaTeX linter (chktex)
        uses: j2kun/chktex-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_lualatex: true
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          path: cv.pdf
          if-no-files-found: error
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          path: cv.log