name: Build (Lualatex)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    name: Build and log errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_lualatex: true
      - name: Upload pdf
        uses: actions/upload-artifact@v2
        with:
          path: cv.pdf
          if-no-files-found: error
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: cv.log