name: Publish PDF release to website

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (stable, prerelease or latest)'     
        required: true
        default: 'latest'
  repository_dispatch:
    types: [dispatch_publish]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  deploy_web:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        env:
          DEFAULT_RELEASE_TYPE: latest
        run: |
          echo "RELEASE_TYPE=${{ github.event.inputs.release_type }} || env.DEFAULT_RELEASE_TYPE" >> $GITHUB_OUTPUT
          echo "::debug::$RELEASE_TYPE"
      - name: Get the release
        uses: rez0n/actions-github-release@v1.8
        id: cv_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "maxpowis/cv"
          type: $RELEASE_TYPE
      - name: Echo release tag name
        run: echo "::debug::Found tag for ($RELEASE_TYPE) release >> ${{ steps.cv_release.outputs.release }}"
      - name: Download cv.pdf from release
        uses: Legion2/download-release-action@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "maxpowis/cv"
          tag: ${{ steps.cv_release.outputs.release }}
          file: cv.pdf
      - name: Publish to website
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN_REPO_WORKFLOW }}
        with:
          source_file: 'cv.pdf'
          destination_repo: 'maxpowis/maxpowis.github.io'
          destination_branch: 'master'
          destination_folder: 'assets'
          user_email: 'max.powis@gmail.com'
          user_name: 'maxpowis'