name: Publish PDF release to website

on:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch_publish]

jobs:
  deploy_web:
    runs-on: ubuntu-latest
    steps:
      - name: Get the release
        uses: pozetroninc/github-action-get-latest-release@master
        id: cv_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "maxpowis/cv"
      - name: Echo release tag name
        run: echo "::debug::Found tag for LATEST release >> ${{ steps.cv_release.outputs.release }}"
      - name: Download all pdf's from release
        uses: robinraju/release-downloader@v1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "maxpowis/cv"
          tag: ${{ steps.cv_release.outputs.release }}
          fileName: '*.pdf'
      - name: Publish all pdf's to website
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN_REPO_WORKFLOW }}
        with:
          source_file: '*.pdf'
          destination_repo: 'maxpowis/maxpowis.github.io'
          destination_branch: 'master'
          destination_folder: 'assets'
          user_email: 'max.powis@gmail.com'
          user_name: 'maxpowis'