name: Create Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Version'
        required: true
        type: string
        default: 'v'
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  version:
    name: Compute Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Get tag from GITHUB_REF
        id: github_ref
        run: |
          echo "::debug::GITHUB_REF=${GITHUB_REF}"
          echo "PUSH_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          echo "::debug::PUSH_TAG=$PUSH_TAG"
      - name: Set release name based on originating event
        id: get_version
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_VERSION: ${{ inputs.tags }}
          PUSH_TAG: ${{ steps.github_ref.outputs.PUSH_TAG }}
        run: |
          echo "::debug::INPUT_VERSION=$INPUT_VERSION"
          if [[ "$EVENT_NAME" == "workflow_dispatch" ]]; then computed_version="$INPUT_VERSION"; else computed_version="$PUSH_TAG"; fi
          echo "VERSION=$computed_version" >> $GITHUB_OUTPUT
          echo "::debug::Version evaluated to $VERSION"
  release:
    name: Create Release for Version
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo release.dat
        run: echo "::debug::Writing 'version = ${{ needs.version.outputs.version }}' to release.dat"
      - name: Update release.dat
        uses: "finnp/create-file-action@1.0.0"
        env:
          FILE_NAME: "release.dat"
          FILE_DATA: "version = ${{ needs.version.outputs.version }}"
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          latexmk_use_lualatex: true
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ needs.version.outputs.version }}
          name: Release ${{ needs.version.outputs.version }}
          draft: false
          prerelease: true
          files: cv.pdf
      - name: Trigger workflow 'Publish PDF release to website'
        uses: peter-evans/repository-dispatch@v2.1.1
        if: ${{ github.event_name=='push' }}
        with:
          token: ${{ secrets.PERSONAL_TOKEN_REPO_WORKFLOW }}
          event-type: dispatch_publish